// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OutOfTheBox.Infrastructure.Persistence;

#nullable disable

namespace OutOfTheBox.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(OutOfTheBoxDbContext))]
    [Migration("20260811050449_AddNuGetCredentialTracking")]
    partial class AddNuGetCredentialTracking
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("OutOfTheBox.Domain.Repositories.GitHostAuthorization", b =>
                {
                    b.Property<string>("Host")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("AuthorizedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Host");

                    b.ToTable("GitHostAuthorizations");
                });

            modelBuilder.Entity("OutOfTheBox.Domain.Repositories.GitHostCredentialHealth", b =>
                {
                    b.Property<string>("Host")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("LastAuthFailureAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("LastAuthSuccessAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Host");

                    b.ToTable("GitHostCredentialHealth");
                });

            modelBuilder.Entity("OutOfTheBox.Domain.Repositories.NuGetFeedAuthorization", b =>
                {
                    b.Property<string>("FeedUrl")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("AuthorizedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("EncryptedPassword")
                        .HasColumnType("BLOB");

                    b.HasKey("FeedUrl");

                    b.ToTable("NuGetFeedAuthorizations");
                });

            modelBuilder.Entity("OutOfTheBox.Domain.Runs.Run", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Arguments")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ExitCode")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FilePath")
                        .HasColumnType("TEXT");

                    b.Property<long?>("FileSizeBytes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RepositoryPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceUrl")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Stderr")
                        .HasColumnType("TEXT");

                    b.Property<string>("Stdout")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Truncated")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Runs");
                });

            modelBuilder.Entity("OutOfTheBox.Domain.Runs.RunResourceSample", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("CpuPercent")
                        .HasColumnType("REAL");

                    b.Property<long>("RamBytes")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("RunId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RunId", "Timestamp");

                    b.ToTable("RunResourceSamples");
                });
#pragma warning restore 612, 618
        }
    }
}
